name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with: 
          java-version: 1.8
      - name: build
         run: ./gradlew :library:build --stacktrace
      - name: Microsoft C++ Code Analysis Action
        uses: microsoft/msvc-code-analysis-action@v0.1.0


